### ISSUE TITLE
SaleEntry - Menu Items for Different Sale Entry Classes

### ISSUE THREAD

**Issue by yesbabyrun** [yesbabylon/symbiose#138]
## SaleEntry - Menu Items for Different Sale Entry Classes

To ensure uniformity across different sale entry classes (saleEntry, timeEntry, subscriptionEntry), the following updates are needed:

- Add a menu item for `billed` status.
- Homogenize the menus to align with the defined statuses.

**Comment by lucaslaurent04** [comment]
Done while doing #137
