### ISSUE TITLE
sale - receivable assignment

### ISSUE THREAD

**Issue by yesbabyrun** [yesbabylon/symbiose#30]
We should allow arbitrary assignment of receivables to an invoice.

Currently, there is a controller named `sale_receivable_bulk-add-invoice` which creates a new invoice for the "pending receivables". However, we need to:

- Allow adding receivables to a specific invoice.
- Enable selecting one or more receivables from the list and adding them to a specific invoice.

**Comment by lucaslaurent04** [comment]
@cedricfrancoys 

Before an action could be added to a selection widget, now only "Remove" action is shown:

![Image](https://github.com/yesbabylon/symbiose/assets/3625888/d841b103-f8e0-48ae-bad6-04ff3cf3a988)

But action is present in list.selection view:

https://github.com/yesbabylon/symbiose/blob/79c316cb5ade10d7bffc939c7eb2bfb4592b6c42/sale/views/receivable/Receivable.list.selection.json#L6-L19
