### ISSUE TITLE
Identity - Wrong partners_ids in the Identity form

### ISSUE THREAD

**Issue by ghost** [yesbabylon/symbiose#54]
The "partners_ids" attribute does not exist in the Identity class, but it is present in the Identity.form.default.json.

https://github.com/yesbabylon/symbiose/blob/c5e7e4e949836a97faf483ece9c958d6bbf3f6ff/identity/views/Identity.form.default.json#L321-L327

**Comment by yesbabyrun** [comment]
PR merged in [3ae0af0](https://github.com/yesbabylon/symbiose/commit/3ae0af0c7340058dd58bd6e24597d63f00814cd4)
